#
# DEFAULT
#
default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

#
# DEVELOPMENT
#
development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

#
# TEST
#
test:
  adapter: postgresql

#
# PRODUCTION
#
production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>